### ISSUE TITLE
Could it support fields starting with an underscore, "_"?

### ISSUE THREAD

**Issue by canob** [matthewfranglen/postgres-elasticsearch-fdw#18]
Hi,

Are fields starting with an underscore in ElasticSearch, like _index or _source, supported? Because they showed empty whe I do a select in the foreing table of PostgreSQL, and they have information in Elasticsearch.
In the foreign table definition, I tried with **index**, **_index**, and **"_index"** without any luck.

Thanks in advance!

**Comment by matthewfranglen** [comment]
The fields in _source are what the table exposes. See [the code](https://github.com/matthewfranglen/postgres-elasticsearch-fdw/blob/master/pg_es_fdw/__init__.py#L262).

To access the index you should use the `rowid_column` as described in the [create foreign table](https://github.com/matthewfranglen/postgres-elasticsearch-fdw#create-the-foreign-table) section of the readme.

**Comment by matthewfranglen** [comment]
Hey is this still an issue?

**Comment by canob** [comment]
No, its ok. Thanks for your help.
