### ISSUE TITLE
I cant't connect with ElasticSearch from AWS

### ISSUE THREAD

**Issue by krisnamourt** [matthewfranglen/postgres-elasticsearch-fdw#23]
I'm trying to test this wrapper with AWS Elastic Search
My Elastic Object

```
 {
                "_index": "twitter",
                "_type": "_doc",
                "_id": "1",
                "_score": 1.0,
                "_source": {
                    "User": "olivere",
                    "Message": "Take Five",
                    "Retweets": 0
                }
            }
```
    My foreing table
    
```
    CREATE FOREIGN TABLE articles_es
    (
        "User" TEXT,
        Message TEXT,
        Retweets NUMERIC
    )
SERVER multicorn_es
OPTIONS
    (
        host 'https://vpc-my-elastic-jxd4u4p3jwj4sl00ydrardrt7i.us-east-1.es.amazonaws.com',
        port '80',
        index 'twitter',
        type '',
        rowid_column 'id',
        query_column 'query',
        query_dsl 'false',
        score_column 'score',
        default_sort 'last_updated:desc',
        sort_column 'sort',
        refresh 'false',
        complete_returning 'false',
        timeout '20',
        username '',
        password ''
    )
;
```

I got this error

```
SQL Error [XX000]: ERROR: COUNT for /twitter failed: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5373493750>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5373493750>: Failed to establish a new connection: [Errno -2] Name or service not known)
```

**Comment by matthewfranglen** [comment]
You've got `<my url>` in the `host`. The error is `Name or service not known`, so your problem is that whatever you have put in the `host` doesn't resolve from the postgres machine. The host is not a url, it's a hostname.

**Comment by krisnamourt** [comment]
Yeah, AWS Elasticsearch is accessed by a URL not a hostname or IP

**Comment by matthewfranglen** [comment]
Yes and the URL has a hostname and possibly an IP in it.

**Comment by krisnamourt** [comment]
@matthewfranglen I put a similar URL and also saw that on AWS I have to use port 80, but I got the same error

I'm using a postgres inside a container and I was able to use another data wrapper for mysql, below is the elastic response usning postman
![image](https://user-images.githubusercontent.com/69539484/111488037-a3fa0080-8717-11eb-961b-a2fd10955c54.png)

**Comment by matthewfranglen** [comment]
I'm sure this can be solved. Could you provide the url that you put into postmaster or the aws provided one?

**Comment by krisnamourt** [comment]
The URL is this: https://vpc-tst-catalog-jxd4u4p3jwj4sl63ydrardrt7i.us-east-1.es.amazonaws.com

As I mention before I'm using a postgres container, this one postgres:10.16
I also deployed a local elastic using this image elasticsearch:7.10.1 I'm able to access through postman but no from my postgres.

**Comment by matthewfranglen** [comment]
Can you try:

```
    CREATE FOREIGN TABLE articles_es
    (
        "User" TEXT,
        Message TEXT,
        Retweets NUMERIC
    )
SERVER multicorn_es
OPTIONS
    (
        host 'vpc-my-elastic-jxd4u4p3jwj4sl00ydrardrt7i.us-east-1.es.amazonaws.com',
        port '443',
        index 'twitter',
        type '',
        rowid_column 'id',
        query_column 'query',
        query_dsl 'false',
        score_column 'score',
        default_sort 'last_updated:desc',
        sort_column 'sort',
        refresh 'false',
        complete_returning 'false',
        timeout '20',
        username '',
        password ''
    )
;
```

**Comment by matthewfranglen** [comment]
if you leave out the username and password then they won't be used. Having them as empty strings is not the same as not having them.

**Comment by krisnamourt** [comment]
Cool, I removed username and password and worked, thanks!

**Comment by matthewfranglen** [comment]
I think that concludes this ticket then.
