### ISSUE TITLE
Authentication by headers

### ISSUE THREAD

**Issue by Matthiosso** [matthewfranglen/postgres-elasticsearch-fdw#28]
Hi,

Thank you for your very helpful project!

Currently, I’m using an authentication system passing identifiers using headers in the request to ElasticSearch. 

Would it be possible to customize headers in the request made to ElasticSearch please ?

Thank you for your help,
Matthiosso

**Comment by matthewfranglen** [comment]
Hi,

I've been thinking about this and I don't think there is a clean way to set arbitrary headers using options as there are just too many potential headers to set. I suggest that you fork this repository and add the required headers.

The elasticsearch client is created [here](https://github.com/matthewfranglen/postgres-elasticsearch-fdw/blob/master/pg_es_fdw/__init__.py#L70-L72) and you can find the uses of it by just searching for _client_ (e.g. [here](https://github.com/matthewfranglen/postgres-elasticsearch-fdw/blob/master/pg_es_fdw/__init__.py#L90-L96) it is used to get the approximate row counts).

I'm closing this ticket as I am not going to add this feature. Please don't be discouraged. If you want more help I would be happy to provide it.
