### ISSUE TITLE
Problem with current version elasticsearch==7.16.0

### ISSUE THREAD

**Issue by eshkinkot** [matthewfranglen/postgres-elasticsearch-fdw#29]
With elasticsearch==7.16.0 I have this error:
```
ERROR:  SEARCH for /index-name failed: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [] in order to sort on')
```

With previous elasticsearch==7.14.2 all work correctly.

**Comment by matthewfranglen** [comment]
Hi,

Thanks for opening this issue. I'll have a look into the problem and get back to you.

**Comment by matthewfranglen** [comment]
Hey sorry for the very very late response. The most recent release, 0.11.2, fixes this issue. The underlying problem was that the sort field defaulted to the empty string. The older versions of elasticsearch took this as no sorting, while the newer ones are stricter.
