### ISSUE TITLE
Test ES 8

### ISSUE THREAD

**Issue by matthewfranglen** [matthewfranglen/postgres-elasticsearch-fdw#35]
Is this compatible?

**Comment by kaismh** [comment]
Anyone tried it with ES 8?

**Comment by canob** [comment]
Anyone tried with OpenSearch 1.x.x and OpenSearch 2.x.x???

**Comment by yosva** [comment]
Hi, thanks a lot for your FWD. I'm using it on ES8, after a little fix: add scheme param. I've just made a PR fot that. Regards

**Comment by matthewfranglen** [comment]
Version 0.12.0 supports elasticsearch 8 and all the tests pass.
