### ISSUE TITLE
docker pg15 install issue

### ISSUE THREAD

**Issue by MihaiRaduSandu** [matthewfranglen/postgres-elasticsearch-fdw#37]
Hello,

It seems something has changed with the python3 or python3-pip packages, as meanwhile they implemented "externally managed" base environments.
https://peps.python.org/pep-0668/#specification
As a result, the docker image fails [Dockerfile PG15](https://github.com/matthewfranglen/postgres-elasticsearch-fdw/blob/master/tests/docker/pg-15/Dockerfile) at line PYTHON_OVERRIDE=python3 make install, more specifically when it tries to run pip3 install .
I tried fixing it by myself, I also tried to install an earlier version of python3 but it seems they are not available anymore, and I am not very good at installing packages in linux.
I would greatly appreciate it if you could offer me a solution and maybe update the dockerfile.

Thank you,
Mihai

**Comment by matthewfranglen** [comment]
Hey sorry to get to this so late. The dockerfile now has a flag to indicate that the package should be installed globally:

https://github.com/matthewfranglen/postgres-elasticsearch-fdw/blob/main/tests/docker/pg-15/Dockerfile#L22

You can do 

```
pip3 install elasticsearch --break-system-packages
```

with the appropriate version constraint.
