### ISSUE TITLE
question: can I define a table without an index and select the index in the query filtering?

### ISSUE THREAD

**Issue by MihaiRaduSandu** [matthewfranglen/postgres-elasticsearch-fdw#43]
Hello,

We have an ES7 with indexes that are created each month and older indexes are deleted.
One solution would be to create a cron in pg and delete and recreate the table based on the index name constructed adhoc.

But I was looking if there would be a more elegant solution to this problem.

I saw I can create a table without an index, which is great, basically I suppose it will return all the objects from all the indexes, and if I put a general field like _id it will return results, so it works without an index.

But further on, I can't find a way to filter only based on the index name. 
I tried adding a field _index but it returns that the field does not exist.
I tried adding an index filtering in the WHERE query =, but it returns index parameter is not supported.

I was hoping maybe you know of a way to do this, or wondering if you could add index filtering. 

Thank you,
Mihai

**Comment by MihaiRaduSandu** [comment]
So as I'm just learning ES, I just found out that I can define the index as index_prefix_*, and it will actually search in all the indexes with the same prefix, which solved my problem.
But if there is another way, please add it here.
Otherwise the post can be closed. 
Thank you

**Comment by matthewfranglen** [comment]
That's a neat solution. As the _index field is metadata it's not exposed to the columns. Changing this would mean altering https://github.com/matthewfranglen/postgres-elasticsearch-fdw/blob/main/pg_es_fdw/columns.py to add another class much like the IdColumn. Given that you have a solution I'm happy to close this issue.
