### ISSUE TITLE
could  it support the es x-pack basic-authentication?

### ISSUE THREAD

**Issue by yasz** [matthewfranglen/postgres-elasticsearch-fdw#9]
Thank you very much！

**Comment by matthewfranglen** [comment]
Hey,

Thanks for the suggestion. I'll have a look into this and see if I can enable it.

**Comment by matthewfranglen** [comment]
I've released a new version that has basic auth support via the `username` and `password` options on table creation. I've added a test for this using es 6 (as the docker container for that can start with authentication enabled), and it passes so I am reasonably sure this works.

This has been released as version 0.7.4. It would be great if you could test if this works.

If this does not work with your setup please provide detailed instructions regarding how to reproduce your environment - ideally via a dockerfile that will launch elasticsearch with your configuration.

**Comment by matthewfranglen** [comment]
I think this is resolved. Please let me know if it is not.

**Comment by playerla** [comment]
Hi, seems not to work :
https://github.com/matthewfranglen/postgres-elasticsearch-fdw/blob/576ccd30598ff110fcc7d6f67e5b6fcd12af8926/pg_es_fdw/options.py#L52 use Basic Auth but it's only exist in ES8
https://discuss.elastic.co/t/basic-authentication-not-working-via-python-client/301435 
(https://elasticsearch-py.readthedocs.io/en/v7.17.1/api.html#elasticsearch)

**Comment by bw-matthew** [comment]
Opened https://github.com/matthewfranglen/postgres-elasticsearch-fdw/issues/42 to track that. This did work for version 6!
